In [1]:
rm(list = ls())

library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
msleep

   name                           genus         vore    order
1  Cheetah                        Acinonyx      carni   Carnivora
2  Owl monkey                     Aotus         omni    Primates
3  Mountain beaver                Aplodontia    herbi   Rodentia
4  Greater short-tailed shrew     Blarina       omni    Soricomorpha
5  Cow                            Bos           herbi   Artiodactyla
6  Three-toed sloth               Bradypus      herbi   Pilosa
7  Northern fur seal              Callorhinus   carni   Carnivora
8  Vesper mouse                   Calomys       NA      Rodentia
9  Dog                            Canis         carni   Carnivora
10 Roe deer                       Capreolus     herbi   Artiodactyla
11 Goat                           Capri         herbi   Artiodactyla
12 Guinea pig                     Cavis         herbi   Rodentia
13 Grivet                         Cercopithecus omni    Primates
14 Chinchilla                     Chinchilla    herbi   Rodentia
15 Star-nosed mole                Condylura     omni    Soricomorpha
16 African giant pouched rat      Cricetomys    omni    Rodentia
17 Lesser short-tailed shrew      Cryptotis     omni    Soricomorpha
18 Long-nosed armadillo           Dasypus       carni   Cingulata
19 Tree hyrax                     Dendrohyrax   herbi   Hyracoidea
20 North American Opossum         Didelphis     omni    Didelphimorphia
21 Asian elephant                 Elephas       herbi   Proboscidea
22 Big brown bat                  Eptesicus     insecti Chiroptera
23 Horse                          Equus         herbi   Perissodactyla
24 Donkey                         Equus         herbi   Perissodactyla
25 European hedgehog              Erinaceus     omni    Erinaceomorpha
26 Patas monkey                   Erythrocebus  omni    Primates
27 Western american chipmunk      Eutamias      herbi   Rodentia
28 Domestic cat                   Felis         carni   Carnivora
29 Galago                         Galago        omni    Primates
30 Giraffe                        Giraffa       herbi   Artiodactyla
⋮  ⋮                              ⋮             ⋮       ⋮
54 Baboon                         Papio         omni    Primates
55 Desert hedgehog                Paraechinus   NA      Erinaceomorpha
56 Potto                          Perodicticus  omni    Primates
57 Deer mouse                     Peromyscus    NA      Rodentia
58 Phalanger                      Phalanger     NA      Diprotodontia
59 Caspian seal                   Phoca         carni   Carnivora
60 Common porpoise                Phocoena      carni   Cetacea
61 Potoroo                        Potorous      herbi   Diprotodontia
62 Giant armadillo                Priodontes    insecti Cingulata
63 Rock hyrax                     Procavia      NA      Hyracoidea
64 Laboratory rat                 Rattus        herbi   Rodentia
65 African striped mouse          Rhabdomys     omni    Rodentia
66 Squirrel monkey                Saimiri       omni    Primates
67 Eastern american mole          Scalopus      insecti Soricomorpha
68 Cotton rat                     Sigmodon      herbi   Rodentia
69 Mole rat                       Spalax        NA      Rodentia
70 Arctic ground squirrel         Spermophilus  herbi   Rodentia
71 Thirteen-lined ground squirrel Spermophilus  herbi   Rodentia
72 Golden-mantled ground squirrel Spermophilus  herbi   Rodentia
73 Musk shrew                     Suncus        NA      Soricomorpha
74 Pig                            Sus           omni    Artiodactyla
75 Short-nosed echidna            Tachyglossus  insecti Monotremata
76 Eastern american chipmunk      Tamias        herbi   Rodentia
77 Brazilian tapir                Tapirus       herbi   Perissodactyla
78 Tenrec                         Tenrec        omni    Afrosoricida
79 Tree shrew                     Tupaia        omni    Scandentia
80 Bottle-nosed dolphin           Tursiops      carni   Cetacea
81 Genet                          Genetta       carni   Carnivora
82 Arctic fox                     Vulpes        carni   Carnivora
83 Red fox                        Vulpes        carni   Carnivora
   conservation sleep_total sleep_rem sleep_cycle awake brainwt bodywt
1  lc           12.1         NA              NA   11.9       NA   50.000
2  NA           17.0        1.8              NA    7.0  0.01550    0.480
3  nt           14.4        2.4              NA    9.6       NA    1.350
4  lc           14.9        2.3       0.1333333    9.1  0.00029    0.019
5  domesticated  4.0        0.7       0.6666667   20.0  0.42300  600.000
6  NA           14.4        2.2       0.7666667    9.6       NA    3.850
7  vu            8.7        1.4       0.3833333   15.3       NA   20.490
8  NA            7.0         NA              NA   17.0       NA    0.045
9  domesticated 10.1        2.9       0.3333333   13.9  0.07000   14.000
10 lc            3.0         NA              NA   21.0  0.09820   14.800
11 lc            5.3        0.6              NA   18.7  0.11500   33.500
12 domesticated  9.4        0.8       0.2166667   14.6  0.00550    0.728
13 lc           10.0        0.7              NA   14.0       NA    4.750
14 domesticated 12.5        1.5       0.1166667   11.5  0.00640    0.420
15 lc           10.3        2.2              NA   13.7  0.00100    0.060
16 NA            8.3        2.0              NA   15.7  0.00660    1.000
17 lc            9.1        1.4       0.1500000   14.9  0.00014    0.005
18 lc           17.4        3.1       0.3833333    6.6  0.01080    3.500
19 lc            5.3        0.5              NA   18.7  0.01230    2.950
20 lc           18.0        4.9       0.3333333    6.0  0.00630    1.700
21 en            3.9         NA              NA   20.1  4.60300 2547.000
22 lc           19.7        3.9       0.1166667    4.3  0.00030    0.023
23 domesticated  2.9        0.6       1.0000000   21.1  0.65500  521.000
24 domesticated  3.1        0.4              NA   20.9  0.41900  187.000
25 lc           10.1        3.5       0.2833333   13.9  0.00350    0.770
26 lc           10.9        1.1              NA   13.1  0.11500   10.000
27 NA           14.9         NA              NA    9.1       NA    0.071
28 domesticated 12.5        3.2       0.4166667   11.5  0.02560    3.300
29 NA            9.8        1.1       0.5500000   14.2  0.00500    0.200
30 cd            1.9        0.4              NA   22.1       NA  899.995
⋮  ⋮            ⋮           ⋮         ⋮           ⋮     ⋮       ⋮
54 NA            9.4        1.0       0.6666667   14.60 0.18000  25.235
55 lc           10.3        2.7              NA   13.70 0.00240   0.550
56 lc           11.0         NA              NA   13.00      NA   1.100
57 NA           11.5         NA              NA   12.50      NA   0.021
58 NA           13.7        1.8              NA   10.30 0.01140   1.620
59 vu            3.5        0.4              NA   20.50      NA  86.000
60 vu            5.6         NA              NA   18.45      NA  53.180
61 NA           11.1        1.5              NA   12.90      NA   1.100
62 en           18.1        6.1              NA    5.90 0.08100  60.000
63 lc            5.4        0.5              NA   18.60 0.02100   3.600
64 lc           13.0        2.4       0.1833333   11.00 0.00190   0.320
65 NA            8.7         NA              NA   15.30      NA   0.044
66 NA            9.6        1.4              NA   14.40 0.02000   0.743
67 lc            8.4        2.1       0.1666667   15.60 0.00120   0.075
68 NA           11.3        1.1       0.1500000   12.70 0.00118   0.148
69 NA           10.6        2.4              NA   13.40 0.00300   0.122
70 lc           16.6         NA              NA    7.40 0.00570   0.920
71 lc           13.8        3.4       0.2166667   10.20 0.00400   0.101
72 lc           15.9        3.0              NA    8.10      NA   0.205
73 NA           12.8        2.0       0.1833333   11.20 0.00033   0.048
74 domesticated  9.1        2.4       0.5000000   14.90 0.18000  86.250
75 NA            8.6         NA              NA   15.40 0.02500   4.500
76 NA           15.8         NA              NA    8.20      NA   0.112
77 vu            4.4        1.0       0.9000000   19.60 0.16900 207.501
78 NA           15.6        2.3              NA    8.40 0.00260   0.900
79 NA            8.9        2.6       0.2333333   15.10 0.00250   0.104
80 NA            5.2         NA              NA   18.80      NA 173.330
81 NA            6.3        1.3              NA   17.70 0.01750   2.000
82 NA           12.5         NA              NA   11.50 0.04450   3.380
83 NA            9.8        2.4       0.3500000   14.20 0.05040   4.230

In [3]:
Q0 <- msleep %>%
  select(name, vore, conservation, sleep_total) %>%
  filter(vore=="carni", !is.na(conservation)) %>% 
  group_by(conservation) %>% 
  summarize(sleep_time_med = round(median(sleep_total, na.rm=TRUE),2)) %>%
  as.data.frame()

Q0

  conservation sleep_time_med
1 cd            2.70
2 domesticated 11.30
3 en           15.80
4 lc           14.50
5 nt           10.40
6 vu            7.15

In [4]:
Q1 <- msleep |>
  filter(vore == 'carni' & conservation == 'lc') |>
  summarise(var = var(sleep_total)) |>
  mutate(var = round(var, 2)) |>
  as.data.frame()

Q1

  var
1 26.35

In [5]:
Q2 <- msleep |>
        mutate( ratio = sleep_total / sleep_rem) |>
        filter(order == 'Rodentia', rna.rm = TRUE) |>
        arrange(desc(ratio)) |>
        head(1) |>
        select(name) |>
        as.data.frame()
        
Q2

  name
1 Guinea pig

In [6]:
Q3 <- msleep |>
        mutate(ratio = bodywt/brainwt) |>
        filter(ratio > 100 & order == 'Primates') |>
        nrow() |>
        as.data.frame()

Q3

  nrow(filter(mutate(msleep, ratio = bodywt/brainwt), ratio > 100 & order == "Primates"))
1 3

In [7]:
Q4 <- msleep |>
        filter(!is.na(sleep_total)) |>
        group_by(conservation) |>
        summarise(
          mean_sleep = mean(sleep_total, na.rm = TRUE),
          var_sleep = var(sleep_total, na.rm = TRUE)
        ) |>
        filter(!is.na(conservation)) |>
        mutate(
        mean_sleep = round(mean_sleep, 2), 
        var_sleep = round(var_sleep, 2)) |>
        as.data.frame()

Q4

  conservation mean_sleep var_sleep
1 cd            2.30       0.32
2 domesticated  7.58      14.46
3 en           13.03      39.45
4 lc           11.44      21.80
5 nt           12.97       3.84
6 vu            6.93      14.34

In [8]:
Q5 <- msleep |>
        filter(vore == 'herbi' & conservation == 'domesticated' & sleep_total > 12) |>
        select(name) |>
        as.data.frame()

Q5

  name
1 Chinchilla