In [3]:
rm(list = ls())

library(tidyverse) 
pizza <- read_csv('pizza.csv')

Rows: 1266 Columns: 12
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (5): day, date, operator, branch, driver
dbl (7): time, temperature, bill, pizzas, free_wine, got_wine, discount_cust...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [6]:
pizza

     day      date      time     operator branch driver    temperature bill
1    Thursday 1-May-14  35.12837 Laura    East   Bruno     68.28772    58.4
2    Thursday 1-May-14  25.20307 Melissa  East   Salvatore 70.99779    26.4
3    Thursday 1-May-14  45.64340 Melissa  West   Salvatore 53.39415    58.1
4    Thursday 1-May-14  29.37430 Melissa  East   Salvatore 70.30660    35.2
5    Thursday 1-May-14  29.99461 Melissa  West   Salvatore 71.50169    38.4
6    Thursday 1-May-14  40.25432 Melissa  Centre Bruno     60.75950    61.8
7    Thursday 1-May-14  48.72861 Laura    West   Bruno     58.25870    57.9
8    Thursday 1-May-14  34.02772 Melissa  West   Mario     68.12793    35.8
9    Thursday 1-May-14  28.20943 Laura    Centre Mario     64.94661    36.6
10   Thursday 1-May-14  37.95479 Melissa  Centre Bruno     60.00738    44.8
11   Thursday 1-May-14  42.07956 Melissa  Centre Bruno     65.53872    49.5
12   Thursday 1-May-14  24.80794 Laura    East   Mario     62.78967    49.7
13   Thursday 1-May-14  28.32022 Melissa  West   Mario     69.88133    41.1
14   Thursday 1-May-14  25.45198 Melissa  Centre Salvatore 74.86141    42.9
15   Thursday 1-May-14  23.78428 Laura    West   Bruno     64.62646    25.9
16   Thursday 1-May-14  40.71921 Melissa  West   Salvatore 71.21695    41.5
17   Thursday 1-May-14  26.13680 Melissa  Centre Mario     59.66241    34.9
18   Thursday 1-May-14  41.77403 Melissa  East   Bruno     65.92437    42.4
19   Thursday 1-May-14  25.15867 Laura    East   Mario     75.12395    27.3
20   Thursday 1-May-14  36.73024 Melissa  Centre Bruno     65.80071    47.7
21   Thursday 1-May-14  47.78338 Melissa  Centre Mario     66.10353    63.7
22   Thursday 1-May-14  35.19658 Laura    East   Salvatore 66.17845    31.3
23   Thursday 1-May-14  30.64514 Melissa  West   Bruno     66.54460    62.7
24   Thursday 1-May-14  25.01187 Melissa  East   Salvatore 62.48674    37.7
25   Thursday 1-May-14  44.28090 Melissa  Centre Bruno     60.66103    47.5
26   Thursday 1-May-14  37.98576 Melissa  Centre Bruno     49.30972    61.3
27   Thursday 1-May-14  26.35593 Laura    Centre Salvatore 68.21574    48.9
28   Thursday 1-May-14  31.66187 Melissa  West   Salvatore 63.41108    27.0
29   Thursday 1-May-14  31.52628 Melissa  West   Mario     70.26729    45.5
30   Thursday 1-May-14  40.89841 Melissa  West   Salvatore 63.38302    49.6
⋮    ⋮        ⋮         ⋮        ⋮        ⋮      ⋮         ⋮           ⋮
1237 Saturday 31-May-14 34.89259 Laura    West   Mario     70.72376    31.5
1238 Saturday 31-May-14 35.28230 Melissa  West   Luigi     57.28018    54.5
1239 Saturday 31-May-14 28.09136 Laura    East   Mario     69.20633    45.1
1240 Saturday 31-May-14 47.25236 Laura    Centre Bruno     57.79677    39.9
1241 Saturday 31-May-14 37.72636 Laura    Centre Bruno     60.42162    58.1
1242 Saturday 31-May-14 43.47907 Melissa  West   Domenico  55.93895    28.7
1243 Saturday 31-May-14 35.72673 Melissa  East   Luigi     69.88779    32.0
1244 Saturday 31-May-14 21.31447 Laura    East   Domenico  74.90202    29.7
1245 Saturday 31-May-14 36.73513 Laura    West   Salvatore 56.15431    55.1
1246 Saturday 31-May-14 30.59714 Laura    West   Domenico  66.24100    58.6
1247 Saturday 31-May-14 39.61529 Laura    West   Luigi     60.80231    39.2
1248 Saturday 31-May-14 35.21520 Laura    Centre Salvatore 56.30333    47.1
1249 Saturday 31-May-14 30.63879 Laura    East   Domenico  66.67235    25.2
1250 Saturday 31-May-14 34.35697 Laura    Centre Bruno     61.16477    50.4
1251 Saturday 31-May-14 34.23362 Laura    West   Bruno     66.91446    52.0
1252 Saturday 31-May-14 37.86678 Melissa  West   Bruno     56.22962    55.8
1253 Saturday 31-May-14 40.86872 Laura    West   Luigi     65.63442    37.2
1254 Saturday 31-May-14 42.31477 Laura    Centre Salvatore 66.35179    48.5
1255 Saturday 31-May-14 29.13346 Laura    East   Salvatore 61.44568    38.9
1256 Saturday 31-May-14 42.41926 Melissa  Centre Salvatore 64.76123    52.9
1257 Saturday 31-May-14 26.36247 Laura    Centre Domenico  66.16404    45.6
1258 Saturday 31-May-14 34.32363 Laura    Centre Luigi     47.16329    71.3
1259 Saturday 31-May-14 39.17278 Laura    East   Domenico  54.04255    31.4
1260 Saturday 31-May-14 36.29089 Melissa  West   Salvatore 57.27154    40.0
1261 Saturday 31-May-14 42.90128 Melissa  Centre Bruno     55.96467    49.8
1262 Saturday 31-May-14 38.63942 Laura    West   Mario     63.12642    46.7
1263 Saturday 31-May-14 33.81297 Laura    East   Domenico  56.30273    32.0
1264 Saturday 31-May-14 33.14008 Laura    Centre Luigi     57.97717    45.7
1265 Saturday 31-May-14 36.88055 Laura    Centre Salvatore 52.79583    39.0
1266 Saturday 31-May-14 35.73753 Melissa  West   Bruno     58.64276    42.7
     pizzas free_wine got_wine discount_customer
1    4      0         0        1
2    2      0         0        0
3    3      1         0        0
4    3      0         0        0
5    2      0         0        0
6    4      1         1        0
7    3      1         1        0
8    2      0         0        0
9    2      0         0        0
10   5      0         0        0
11   4      1         0        0
12   3      0         0        0
13   1      0         0        0
14   1      0         0        0
15   1      0         0        0
16   6      1         1        0
17   3      0         0        0
18   4      1         1        1
19   1      0         0        0
20   4      0         0        1
21   2      1         1        1
22   3      0         0        0
23   4      0         0        1
24   1      0         0        0
25   3      1         1        0
26   6      0         0        0
27   5      0         0        0
28   2      0         0        0
29   3      0         0        0
30   6      1         1        0
⋮    ⋮      ⋮         ⋮        ⋮
1237 2      0         0        0
1238 3      0         0        0
1239 2      0         0        1
1240 7      1         1        1
1241 3      0         0        0
1242 3      1         0        0
1243 3      0         0        1
1244 5      0         0        1
1245 7      0         0        0
1246 2      0         0        0
1247 1      0         0        0
1248 4      0         0        0
1249 1      0         0        0
1250 3      0         0        0
1251 7      0         0        1
1252 6      0         0        0
1253 3      1         1        0
1254 4      1         1        0
1255 2      0         0        0
1256 4      1         1        1
1257 2      0         0        0
1258 4      0         0        1
1259 3      0         0        0
1260 2      0         0        0
1261 4      1         1        1
1262 4      0         0        0
1263 1      0         0        0
1264 3      0         0        1
1265 5      0         0        1
1266 3      0         0        0

In [7]:
Q1 <- pizza |>
  group_by(driver) |>
  filter(
    free_wine == 1 &
    discount_customer == 1 &
    pizzas > 4
  ) |>
  select(driver) |>
  as.data.frame()

Q1

  driver
1 Salvatore
2 Salvatore
3 Salvatore
4 Salvatore
5 Mario
6 Mario
7 Salvatore
8 Luigi
9 Bruno

In [8]:
Q2 <- pizza |>
      mutate(ratio = bill / pizzas) |>
      summarise(mean_ratio = round(mean(ratio),2)) |>
      as.data.frame()

Q2

  mean_ratio
1 17.27

In [9]:
Q3 <- pizza |>
        group_by(day) |>
        summarise(var_pizzas = round(var(pizzas),2)) |>
        as.data.frame()

Q3

  day       var_pizzas
1 Friday    2.10
2 Monday    1.94
3 Saturday  2.20
4 Sunday    2.09
5 Thursday  2.13
6 Tuesday   2.07
7 Wednesday 2.64

In [10]:
Q4 <- pizza |>
        group_by(operator) |>
        arrange(desc(bill)) |>
        select(operator) |>
        head(1) |>
        as.data.frame()

Q4

  operator
1 Melissa

In [11]:
Q5 <- pizza |>
  group_by(day,driver) |>
  summarise(count = sum(free_wine, na.rm = TRUE), .groups = 'drop') |>
  filter(count == max(count)) |>
  as.data.frame()

Q5

  day     driver count
1 Tuesday Bruno  20